version: '3.7'

services:
  theia:
    image: theiaide/theia-full:1.14.0
    container_name: theia
    networks:
      - red
    restart: always
    ports:
      - "3030:3000"
    volumes:
      - /root/project:/home/project:cached
      - /var/run/docker.sock:/tmp/docker.sock:ro

networks:
  red:
    driver: bridge
